### ISSUE TITLE
UI Suggestion + one question to ask 

### ISSUE THREAD

**Issue by Greatz08** [pingcap/autoflow#400]
![image](https://github.com/user-attachments/assets/82868581-de7d-406d-81e5-cd70dfda9b06)

GIve option to to close this side menu for better clear view of the message or make this line which i highlighted bigger and draggable when been hovered over so that people can expand according to their own preference (Both options can give better user experience  in my opinion) 

Now i have one question which is - where is signup button because i could only see login option only

![image](https://github.com/user-attachments/assets/fe59794f-70d0-4ad3-a4b9-4fd44f654dab)

**Comment by 634750802** [comment]
Hi @Greatz08, thanks for your feedback. I'll try shadcn's new [sidebar component](https://ui.shadcn.com/docs/components/sidebar) later.

This UI is currently a "playground for admin" rather than a "client". Sign in button was designed for admin for configure the app.

We use this service as a backend for product official site widgets (e.g. the "ask tidb.ai" button on header of https://docs.pingcap.com)

**Comment by 634750802** [comment]
Hi @Greatz08, tidb.ai use the new sidebar now.
